//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DORDUNCU_PROJE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteriler
    {
        public int Id { get; set; }
        public string AdSoyadi { get; set; }
        public string TcKimlik { get; set; }
        public string Telefon { get; set; }
        public string Eposta { get; set; }
    }
}
