//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dersler
    {
        public int DersNo { get; set; }
        public int DersKredisi { get; set; }
        public int DersAKTS { get; set; }
        public int OgrenciNo { get; set; }
        public int OgrenciOgrenciNo { get; set; }
    
        public virtual Ogrenci Ogrenci { get; set; }
    }
}
