//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogrenci
    {
        public Ogrenci()
        {
            this.Derslers = new HashSet<Dersler>();
        }
    
        public int OgrenciNo { get; set; }
        public string AdSoyadi { get; set; }
        public int Yas { get; set; }
    
        public virtual ICollection<Dersler> Derslers { get; set; }
    }
}
