//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proje
    {
        public int ProjeKodu { get; set; }
        public string ProjeAdi { get; set; }
        public Nullable<int> SorumluPersonelNo { get; set; }
        public Nullable<int> AitOlduguBirimNo { get; set; }
    
        public virtual Birim Birim { get; set; }
        public virtual Personel Personel { get; set; }
    }
}
