//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calisan
    {
        public int CalisanNo { get; set; }
        public string Adsoyad { get; set; }
        public Nullable<int> Yas { get; set; }
        public Nullable<int> Maas { get; set; }
        public string Mezuniyet { get; set; }
        public string Cinsiyet { get; set; }
        public string Memleket { get; set; }
        public string Şube { get; set; }
        public Nullable<int> Prim { get; set; }
    }
}
