//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kiyafet
    {
        public int KiyafetNo { get; set; }
        public string KiyafetAdi { get; set; }
        public string Beden { get; set; }
        public string KumasTipi { get; set; }
        public string Renk { get; set; }
        public string Marka { get; set; }
        public string KiyafetModel { get; set; }
        public string Yas { get; set; }
        public Nullable<int> Adet { get; set; }
        public decimal Fiyat { get; set; }
        public string Mensei { get; set; }
        public string SubeSehir { get; set; }
    }
}
