//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Malzemeler
    {
        public int MalzemeNo { get; set; }
        public string MalzemeAdi { get; set; }
        public decimal Fiyat { get; set; }
        public Nullable<int> Adet { get; set; }
        public string Durum { get; set; }
    }
}
