//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personel()
        {
            this.Projes = new HashSet<Proje>();
        }
    
        public int PersonelNo { get; set; }
        public string PersonelAdSoyadi { get; set; }
        public Nullable<int> CalistigiBirimNo { get; set; }
        public Nullable<int> UnvanKodu { get; set; }
        public Nullable<int> DahilOlduguProjelerNo { get; set; }
        public Nullable<int> YetkiDuzeyi { get; set; }
    
        public virtual Unvan Unvan { get; set; }
        public virtual YetkiDuzeyi YetkiDuzeyi1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proje> Projes { get; set; }
    }
}
